"use strict";

const Types = {
  REQUEST_LOGIN: "REQUEST_LOGIN",
  GENERATE_AUTH_COOKIE: "GENERATE_AUTH_COOKIE",
  GENERATE_AUTH_COOKIE_OK: "GENERATE_AUTH_COOKIE_OK",
  GENERATE_AUTH_COOKIE_ERROR: "GENERATE_AUTH_COOKIE_ERROR",
  VALIDATE_AUTH_COOKIE: "VALIDATE_AUTH_COOKIE"
};

export default Types;
