'use strict';

const Types = {
  GET_POST: 'GET_POST',
  GET_POSTS: 'GET_POSTS',
  CREATE_POST: 'CREATE_POST',
  CLEAR_POSTS: 'CLEAR_POSTS',
  CLEAR_POST: 'CLEAR_POST',
  SET_ARGS: 'SET_ARGS',
  RECEIVE_POST: 'RECEIVE_POST',
  RECEIVE_POSTS: 'RECEIVE_POSTS',
  RECEIVE_COMMENT: 'RECEIVE_COMMENT',

  GET_PAGE: 'GET_PAGE',
  CLEAR_PAGE: 'CLEAR_PAGE',
  RECEIVE_PAGE: 'RECEIVE_PAGE',
};

export default Types;
