'use strict';

export const CREATE_POST = 'CREATE_POST';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const RECEIVE_RECENT_POSTS = 'RECEIVE_RECENT_POSTS';

export const RECEIVE_CATEGORY_INDEX = 'RECEIVE_CATEGORY_INDEX';