'use strict';

export const NETWORK_CHECK_CONNECTION = 'NETWORK_CHECK_CONNECTION';
export const NETWORK_CONNECTION_ONLINE = 'NETWORK_CONNECTION_ONLINE';
export const NETWORK_CONNECTION_OFFLINE = 'NETWORK_CONNECTION_OFFLINE';