'use strict';

const Types = {
  SAVE_USER_DATA: 'SAVE_USER_DATA',
  RECEIVE_USER: 'RECEIVE_USER',
  LIST_USERS: 'LIST_USERS',
  RECEIVE_LIST_USERS: 'RECEIVE_LIST_USERS',
  CREATE_USER: 'CREATE_USER',
  CREATED_USER: 'CREATED_USER',
  UPDATE_USER: 'UPDATE_USER',
  UPDATED_USER: 'UPDATED_USER',
  DELETE_USER: 'DELETE_USER',
  DELETED_USER: 'DELETED_USER',
  LOG_OUT: 'LOG_OUT',
};

export default Types;
